### PR TITLE
Fix incorrect type annotation on `cacheSecretStorageKey`

### PR DESCRIPTION
**Pull request by richvdh**
`cacheSecretStorageKey` is passed a `SecretStorageKeyDescription` (aka a `ISecretStorageKeyInfo`), and has done ever since https://github.com/matrix-org/matrix-js-sdk/pull/1502. `AddSecretStorageKeyOpts`is something else, though until recently some of the properties on `AddSecretStorageKeyOpts` were incorrectly marked as optional, so this went unnoticed since it was broken by https://github.com/matrix-org/matrix-react-sdk/pull/11217.

### CODE REVIEW

**Review by florianduros — APPROVED** [review]

**Comment by richvdh** [comment]
This fixes the error:

```
Error: cypress/support/bot.ts(185,17): error TS2322: Type '{ getCrossSigningKey: (type: string) => any; saveCrossSigningKeys: (k: Record<string, Uint8Array>) => void; cacheSecretStorageKey: (keyId: string, keyInfo: AddSecretStorageKeyOpts, key: Uint8Array) => void; getSecretStorageKey: () => Promise<...>; }' is not assignable to type 'CryptoCallbacks'.
  Types of property 'cacheSecretStorageKey' are incompatible.
    Type '(keyId: string, keyInfo: AddSecretStorageKeyOpts, key: Uint8Array) => void' is not assignable to type '(keyId: string, keyInfo: SecretStorageKeyDescriptionAesV1, key: Uint8Array) => void'.
      Types of parameters 'keyInfo' and 'keyInfo' are incompatible.
        Property 'key' is missing in type 'SecretStorageKeyDescriptionAesV1' but required in type 'AddSecretStorageKeyOpts'.
```

(see https://github.com/matrix-org/matrix-react-sdk/actions/runs/7250359613/job/19750354201#step:5:9  for example)
